name: dhana_resume
description: A new portfolio project.

version: 1.2.2+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^9.0.0-nullsafety
  url_launcher: ^6.0.2
  google_maps_flutter: ^2.0.1
  fl_chart: ^0.20.1
  firebase_core: ^1.0.0 
  firebase_messaging: ^9.0.0
  package_info: ^2.0.0
  http: ^0.13.0
  rxdart: ^0.26.0





  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/ic_launcher.png"


flutter:

  uses-material-design: true

  
