name: dhana_resume
description: A new portfolio project.

version: 1.2.2+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0-nullsafety.5
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^9.0.0-nullsafety
  url_launcher: ^6.0.2
  fl_chart: ^0.20.1
  firebase_core: ^1.0.0 
  firebase_messaging: ^9.0.1
  firebase_analytics: "^8.0.0-dev.2"
  package_info: ^2.0.0
  http: ^0.13.0
  rxdart: ^0.26.0
  built_value: ^8.0.6
  built_collection : ^5.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  build_runner: ^1.12.2
  built_value_generator: ^8.0.6


  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/ic_launcher.png"


flutter:

  uses-material-design: true

  
